[package]
name = "geometric_algebra_implementation"
version = "0.1.0"
edition = "2021"
authors = ["Praneeth Lakshman"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
